<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>도입문의 | NEXORA</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@500;600&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" rel="stylesheet">
<link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/pages/index.css"/><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/pages/inquiry_write.css"/><link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css"/><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/top.css?v=20261002-4"/></head>
<body class="bg-[#f8f9ff] text-[#0b1c30] font-[Inter] min-h-screen"><jsp:include page="/inc/top.jsp" />
<main class="max-w-[1200px] mx-auto px-4 sm:px-6 lg:px-8 py-10 lg:py-14">
<nav class="flex items-center gap-2 text-sm text-slate-500 mb-8"><a class="hover:text-blue-600" href="${pageContext.request.contextPath}/index.jsp">홈</a><span>›</span><a class="hover:text-blue-600" href="${pageContext.request.contextPath}/inquiry/index.jsp">고객센터</a><span>›</span><strong class="text-slate-900">도입문의</strong></nav>
<section class="grid lg:grid-cols-[0.85fr_1.15fr] gap-8 items-start">
<div class="rounded-2xl bg-[#0d1c32] text-white p-8 lg:p-10 shadow-sm"><span class="inline-flex px-3 py-1 rounded-full bg-blue-500/15 text-sky-300 text-xs font-bold tracking-wider">CONTACT NEXORA</span><h1 class="text-3xl lg:text-4xl font-bold mt-5 leading-tight">기업 환경에 맞는<br>솔루션을 상담해보세요.</h1><p class="mt-5 text-slate-300 leading-7">웹 인프라, 보안, SentinelOps 도입 및 기술지원에 대해 문의해 주세요. 담당자가 내용을 확인한 뒤 연락드립니다.</p>
<div class="mt-9 space-y-4 text-sm"><div class="flex gap-3"><span class="material-symbols-outlined text-sky-400">schedule</span><div><b>응답 목표</b><p class="text-slate-400 mt-1">영업일 기준 1차 답변</p></div></div><div class="flex gap-3"><span class="material-symbols-outlined text-sky-400">support_agent</span><div><b>기술지원</b><p class="text-slate-400 mt-1">서비스 장애 및 기술 문의 접수</p></div></div><div class="flex gap-3"><span class="material-symbols-outlined text-sky-400">mail</span><div><b>이메일</b><p class="text-slate-400 mt-1">contact@nexora.co.kr</p></div></div></div></div>
<div class="bg-white rounded-2xl border border-slate-200 p-6 sm:p-8 lg:p-10 shadow-sm"><div class="mb-7"><p class="text-xs font-bold tracking-wider text-blue-600">INQUIRY FORM</p><h2 class="text-2xl font-bold mt-2">문의 정보</h2><p class="text-sm text-slate-500 mt-2">문의 내용을 접수하면 담당 관리자가 확인 후 답변합니다.</p></div>
<c:if test="${not empty errorMessage}"><p class="form-error" role="alert"><c:out value="${errorMessage}"/></p></c:if>
<form method="post" accept-charset="UTF-8" action="${pageContext.request.contextPath}/inquiry/create" class="grid sm:grid-cols-2 gap-5"><input type="hidden" name="csrfToken" value="${csrfToken}">
<label class="text-sm font-semibold">이름 / 담당자명<input required class="mt-2 w-full rounded-lg border border-slate-300 px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500/30 focus:border-blue-500" type="text" name="contactName" value="<c:out value='${param.contactName}'/>" maxlength="100" placeholder="홍길동"></label>
<label class="text-sm font-semibold">이메일<input required class="mt-2 w-full rounded-lg border border-slate-300 px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500/30 focus:border-blue-500" type="email" name="contactEmail" value="<c:out value='${param.contactEmail}'/>" maxlength="150" placeholder="name@company.com"></label>
<label class="text-sm font-semibold">회사명<input class="mt-2 w-full rounded-lg border border-slate-300 px-4 py-3 outline-none focus:border-blue-500" type="text" name="companyName" value="<c:out value='${param.companyName}'/>" maxlength="150" placeholder="회사명"></label>
<label class="text-sm font-semibold">문의 유형<select name="category" class="mt-2 w-full rounded-lg border border-slate-300 px-4 py-3 bg-white outline-none focus:border-blue-500"><option value="GENERAL">일반 문의 / 도입</option><option value="TECHNICAL">기술지원 / SentinelOps</option><option value="ACCOUNT">계정</option><option value="PAYMENT">결제</option><option value="SECURITY">보안</option><option value="OTHER">기타</option></select></label>
<label class="sm:col-span-2 text-sm font-semibold">제목<input required class="mt-2 w-full rounded-lg border border-slate-300 px-4 py-3 outline-none focus:border-blue-500" type="text" name="title" value="<c:out value='${param.title}'/>" maxlength="200" placeholder="문의 제목을 입력하세요"></label>
<label class="sm:col-span-2 text-sm font-semibold">문의 내용<textarea required name="content" maxlength="10000" rows="7" class="mt-2 w-full rounded-lg border border-slate-300 px-4 py-3 outline-none resize-y focus:border-blue-500" placeholder="도입 환경이나 발생한 문제를 작성해 주세요."><c:out value="${param.content}"/></textarea></label>
<div class="sm:col-span-2 flex flex-col sm:flex-row justify-between gap-4 pt-2"><a href="${pageContext.request.contextPath}/inquiry/index.jsp" class="px-5 py-3 rounded-lg border border-slate-300 text-center font-semibold hover:bg-slate-50">고객센터로 돌아가기</a><button class="px-7 py-3 rounded-lg bg-[#0d1c32] text-white font-bold hover:bg-blue-700" type="submit">문의 접수</button></div>
</form><p class="mt-5 text-sm text-slate-500"><a href="${pageContext.request.contextPath}/inquiry/my" class="text-blue-700 hover:underline">로그인 회원은 내 문의에서 진행 상태와 답변을 확인할 수 있습니다.</a></p></div></section></main><jsp:include page="/inc/bottom.jsp" /></body></html>
